Update build-openwrt_v2.yml

diff --git a/.github/workflows/build-openwrt_v2.yml b/.github/workflows/build-openwrt_v2.yml
--- a/.github/workflows/build-openwrt_v2.yml
+++ b/.github/workflows/build-openwrt_v2.yml
@@ -223,23 +223,24 @@ jobs:
       - name: Configure build
         working-directory: openwrt
         run: |
-
           test -n "$DEVICE_PROFILE" || {
-              echo "::error::DEVICE_PROFILE пуст"
-              exit 1
+            echo "::error::DEVICE_PROFILE пуст"
+            exit 1
           }
 
-          cat > .config <<EOF
-CONFIG_TARGET_ath79=y
-CONFIG_TARGET_ath79_generic=y
-CONFIG_TARGET_ath79_generic_DEVICE_${DEVICE_PROFILE}=y
+          cat > .config <<'EOF'
+          CONFIG_TARGET_ath79=y
+          CONFIG_TARGET_ath79_generic=y
+          CONFIG_TARGET_ath79_generic_DEVICE_${DEVICE_PROFILE}=y
 
-CONFIG_DEVEL=y
-CONFIG_CCACHE=y
+          CONFIG_DEVEL=y
+          CONFIG_CCACHE=y
 
-CONFIG_PACKAGE_luci=y
-CONFIG_PACKAGE_uhttpd=y
-EOF
+          CONFIG_PACKAGE_luci=y
+          CONFIG_PACKAGE_uhttpd=y
+          EOF
+
+          sed -i "s/\${DEVICE_PROFILE}/$DEVICE_PROFILE/" .config
 
           make defconfig
 
