Update build-openwrt_v1.yml

diff --git a/.github/workflows/build-openwrt_v1.yml b/.github/workflows/build-openwrt_v1.yml
--- a/.github/workflows/build-openwrt_v1.yml
+++ b/.github/workflows/build-openwrt_v1.yml
@@ -1,4 +1,4 @@
-name: OpenWrt_25.12.05 TL-WDR4300v1.2_16mb
+name: OpenWrt_25.12.05 TL-WDR4300v1.3_16mb
 on:
   workflow_dispatch:
     inputs:
@@ -53,6 +53,45 @@ jobs:
           echo "===== Search image definitions ====="
           grep -RIn "tplink_tl-wdr4300" \
             openwrt/target/linux/ath79/image || true
+
+      ####################################################################
+      ## PATCH IMAGE TYPE: 8MB -> 16MB
+      ####################################################################
+      - name: Change WDR4300 image type to 16MB
+        run: |
+          FILE="openwrt/target/linux/ath79/image/generic-tp-link.mk"
+
+          echo "Using:"
+          echo "$FILE"
+
+          if [ ! -f "$FILE" ]; then
+              echo "::error::File not found: $FILE"
+              exit 1
+          fi
+
+          echo
+          echo "===== BEFORE ====="
+          grep -n -A10 -B2 "Device/tplink_tl-wdr4300" "$FILE"
+
+          echo
+          echo "===== PATCHING ====="
+
+          sed -i '/define Device\/tplink_tl-wdr4300-v1$/,/^endef$/ s/\$(Device\/tplink-8mlzma)/\$(Device\/tplink-16mlzma)/' "$FILE"
+
+          echo
+          echo "===== AFTER ====="
+          grep -n -A10 -B2 "Device/tplink_tl-wdr4300" "$FILE"
+
+          echo
+          echo "===== VERIFY ====="
+
+          grep -A10 "define Device/tplink_tl-wdr4300-v1$" "$FILE" | grep -q '\$(Device/tplink-16mlzma)' || {
+              echo "::error::WDR4300 v1 не переведён на 16mlzma"
+              exit 1
+          }
+
+          echo
+          echo "===== 16MB IMAGE TYPE PATCH SUCCESS ====="
       ####################################################################
       ## PATCH FLASH LAYOUT
       ####################################################################
